# modules.yml
HealthModule:
  Enabled: true

StaminaModule:
  Enabled: true

FireworkBlocker:
  Enabled: false

DamageTracker:
  Enabled: true

MobXPModule:
  Enabled: true

EXPShareModule:
  Enabled: true  # <-- Remember this depends on MobXPModule

RegionLevel:
  Enabled: true

RegionsLevel:
  Enabled: true
  Regions:
    greenhaven_plains:
      BaseLevel: 1
      Weight:
        '2': 66
        '3-10': 33